'use strict';
const $=s=>document.querySelector(s), escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses=['Request Successful','Request partially successful','Request refused','Request was withdrawn','Request was withdrawn due to costs','Public Agency needed','Awaiting response','Response overdue','Request asleep','Information not held','Fee charged','Request awaits classification'];
$('#status').innerHTML+=statuses.map(s=>`<option>${escape(s)}</option>`).join('');
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036fʻ’']/g,'').toLowerCase();let page=1,query='',trigger=null;
function render(){const terms=norm(query).split(/\s+/).filter(Boolean);const matches=records.filter(r=>(!$('#jurisdiction').value||r.jurisdiction===$('#jurisdiction').value)&&(!$('#status').value||r.status===$('#status').value)&&terms.every(t=>norm(r.title+' '+r.agency).includes(t)));const pages=Math.max(1,Math.ceil(matches.length/10));page=Math.min(page,pages);$('#count').textContent=`${matches.length} of ${records.length} saved requests`;$('#results').innerHTML=matches.slice((page-1)*10,page*10).map(r=>{const kind=r.status==='Awaiting response'?'waiting':r.status==='Response overdue'?'overdue':r.status==='Request Successful'?'success':r.status==='Request partially successful'?'partial':'';const date=r.date.split(',');return `<article class="request"><div><h3><button data-record="${records.indexOf(r)}">${escape(r.title)}</button></h3><p class="agency"><button data-agency="${records.indexOf(r)}">${escape(r.agency)}</button><span class="jurisdiction">${escape(r.jurisdiction)}</span></p></div><div><span class="mobile-label">STATUS</span><span class="badge ${kind}">${escape(r.status)}</span></div><div class="listed"><span class="mobile-label">LISTED DATE</span>${escape(date[0].replace('Sept.','Sep'))},${escape(date[1])}<small>${escape(date.slice(2).join(',').trim())}</small></div></article>`}).join('');$('#empty').hidden=matches.length>0;$('#page-label').textContent=matches.length?`Showing ${(page-1)*10+1}–${Math.min(page*10,matches.length)} · Snapshot page ${page} of ${pages}`:'No matching snapshot records';$('#previous').disabled=page===1;$('#next').disabled=page===pages;}
function reset(){query='';$('#query').value='';$('#jurisdiction').value='';$('#status').value='';page=1;render();}
$('#search-form').addEventListener('submit',e=>{e.preventDefault();query=$('#query').value.trim();page=1;render();$('#results-title').focus();});['jurisdiction','status'].forEach(id=>$('#'+id).addEventListener('change',()=>{page=1;render()}));$('#clear').onclick=reset;$('#previous').onclick=()=>{page--;render();$('#results-title').focus()};$('#next').onclick=()=>{page++;render();$('#results-title').focus()};
const infos={agencies:['Public Agencies','The live UIPA directory helps you find the agency that holds a record. This preview keeps agency navigation separate from request search.','https://uipa.org/entities/'],login:['Log In / Sign up','Account access is not connected in this local prototype. No credentials are collected.'],start:['Make a Request','This is a requests-directory redesign only. Request submission is not connected. Requests and responses may be published; review the live service’s guidance before making a request.'],about:['About UIPA.org','UIPA.org is independent of government and helps people find and follow public-records requests to Hawaiʻi agencies.','https://uipa.org/'],faq:['FAQ','For current service guidance, consult UIPA.org’s FAQ.','https://uipa.org/help/faq/'],privacy:['Privacy Statement','Requests and responses may be published. This prototype stores nothing and submits nothing. Consult the live privacy statement for current policies.','https://uipa.org/help/privacy/'],terms:['Terms of Use','This prototype does not create accounts or ask you to accept any terms.','https://uipa.org/help/terms/'],feeds:['Request feeds','RSS and Atom links exist on the live requests directory. This preview does not subscribe you or generate a feed.','https://uipa.org/requests/'],credits:['Credits and sources','The UIPA FAQ credits Code with Aloha with creating the service and Public First Law Center with collaboration and hosting. The live directory still uses older Code for Hawaii wording. Confirm current attribution before launch. This separate concept reproduces public list metadata captured September 28, 2026.','https://uipa.org/help/faq/']};
function show(title,body){trigger=document.activeElement;$('#dialog-content').innerHTML=`<h2 id="dialog-title" tabindex="-1">${escape(title)}</h2>${body}`;$('dialog').showModal();$('#dialog-title').focus();}
document.addEventListener('click',e=>{const info=e.target.closest('[data-info]'),record=e.target.closest('[data-record]'),agency=e.target.closest('[data-agency]');if(e.target.closest('[data-reset]')){reset();$('#results-title').focus();}if(info){const [title,body,url]=infos[info.dataset.info];show(title,`<p>${escape(body)}</p><p class="modal-note">Local demo destination. Nothing is sent or saved.</p>${url?`<a href="${url}" target="_blank" rel="noopener">Open live UIPA page ↗</a>`:''}`);}if(record){const r=records[record.dataset.record];show(r.title,`<dl><dt>Public agency</dt><dd>${escape(r.agency)}</dd><dt>Jurisdiction</dt><dd>${escape(r.jurisdiction)}</dd><dt>Status in snapshot</dt><dd>${escape(r.status)}</dd><dt>Listed timestamp</dt><dd>${escape(r.date)}</dd></dl><p class="modal-note">Saved directory metadata only. Correspondence and attachments are not copied into this preview. A status does not confirm that documents are available here.</p><a href="${r.url}" target="_blank" rel="noopener">Open original request on UIPA.org ↗</a>`);}if(agency){const r=records[agency.dataset.agency];show(r.agency,`<p>${escape(r.jurisdiction)}</p><p class="modal-note">Agency details are not reproduced in this local preview.</p><a href="${r.agencyUrl}" target="_blank" rel="noopener">Open live agency page ↗</a>`);}});
$('#close').onclick=()=>$('dialog').close();$('dialog').addEventListener('close',()=>trigger?.isConnected&&trigger.focus());render();
